GET http://localhost:1234/api/persons

###
GET http://localhost:1234/info

###
DELETE http://localhost:1234/api/persons/1

###
POST http://localhost:1234/api/persons
content-type: application/json

{
  "name" : "",
  "number" : "120154521"
}
